# Generated by Django 6.1 on 2026-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
